### PR TITLE
Landing page stracture

### PR DESCRIPTION
**Pull request by Enockkenya**
**What does this PR do?** 
_relevant Pivotal Tracker Story_ >> STORY ID [click here](https://www.pivotaltracker.com/story/show/159634331) 
This is the landing page when unregistered or registered user visit site then  can get option to sign in or sign up before engaging with the site

**How should this be tested?**
Clone or download the repository. [LINK](https://github.com/Enockkenya/stack-overflow-lite)
Navigate to the UI directory and open the index.html file on a browser.

1 a

2 a

3 a

### CODE REVIEW

**Comment by p8ul** [comment]
Good Stuff.

**Comment by asheuh** [comment]
The UI is perfect.
In the part of description, i would suggest using the following.

#### What does this PR do?

#### How should this be manually tested?

#### What are the relevant pivotal tracker stories?

**Comment by Waitherambugua** [comment]
It looks good.

**Comment by Enockkenya** [comment]
Thank you all @asheuh  noted ill work on that on the next pull request

**Pull request merged**
